"""Add_digital_certificates

Revision ID: bc0bf976ddeb
Revises: 8ccf659d6bb7
Create Date: 2025-11-30 20:07:51.655151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0bf976ddeb'
down_revision: Union[str, Sequence[str], None] = '8ccf659d6bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_content', sa.LargeBinary(), nullable=True),
    sa.Column('password_enc', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['audit_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_certificates_id'), 'digital_certificates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digital_certificates_id'), table_name='digital_certificates')
    op.drop_table('digital_certificates')
    # ### end Alembic commands ###
